name: 'CI'
on: [push, pull_request]
jobs:
  build:
    env:
      RELEASE: false
      VERSION_SUFFIX: -SNAPSHOT
    name: Build
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'ci') || !contains(github.event.head_commit.message, '(github)')"
    steps:
    - if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "RELEASE=true" >> $GITHUB_ENV
        echo "VERSION_SUFFIX=" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Decode Keystore
      id: decode
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'keyring.gpg'
        encodedString: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: Expose
      run: cp ${{ steps.decode.outputs.filePath }} .
    - name: Create Release
      if: env.RELEASE == 'true'
      uses: softprops/action-gh-release@v1
    - uses: gradle/gradle-build-action@v2
      id: build
      with:
        arguments: build
    - name: 'Deploy to Nexus'
      if: steps.build.outcome == 'success'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          publishToGalacticMaven
          -pversion_suffix=${{ env.VERSION_SUFFIX }}
          -Pteamgc.nexus.user=${{ secrets.NEXUS_USER }} 
          -Pteamgc.nexus.password=${{ secrets.NEXUS_PASSWORD }}
