name: 'CI'
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{!startsWith(github.event.head_commit.message, 'ci')}}
    steps:
    - name: Check if DOES NOT startwith
      run: echo ${{!startsWith(github.event.head_commit.message, 'ci')}}
