name: 'CI'

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Execute Gradle build
      env:
        SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_KEYRINGFILE: ${{ secrets.SIGNING_KEYRINGFILE }}
      id: build
      run: ./gradlew checkVariables