name: 'CI'

on: [workflow_dispatch, push]

jobs:
  build:
    env:
      RELEASE: ${{ false }}
      VERSION_SUFFIX: -SNAPSHOT
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Check If Release'
      if: startsWith(github.ref, 'refs/tags/')
      env:
        RELEASE: ${{ true }}
        VERSION_SUFFIX: ${{ null }}
    - name: 'Check Variables'
      run: echo ${{ env.RELEASE }} -> ${{ env.VERSION_SUFFIX }}
    
