name: 'CI'
on: [push, pull_request]
jobs:
  build:
    env:
      MSG: github.event.head_commit.message
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !startsWith(env.MSG, 'ci') || !contains(env.MSG, '(github)') }}
    steps:
    - run: echo RAN
