name: 'CI'

on: [workflow_dispatch, push]

jobs:
  build:
    env:
      RELEASE: ${{ false }}
      VERSION_SUFFIX: -SNAPSHOT
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Check If Release'
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "RELEASE=true" >> $GITHUB_ENV
        echo "VERSION_SUFFIX=" >> $GITHUB_ENV
    - name: 'Should Run Because RELEASE == TRUE'
      if: (${{ env.RELEASE }} == ${{ true }})
      run: echo "CORRECT IT IS A RELEASE"
    - name: 'Should Not Run Because RELEASE == FALSE'
      if: (${{ env.RELEASE }} == ${{ false }})
      run: echo "CORRECT IT IS NOT A RELEASE"
      
      ## TESTING
    - name: 'MIGHT Run Because RELEASE == TRUE'
      if: ${{ env.RELEASE }}
      run: echo "CORRECT IT IS A RELEASE"
    - name: 'MIGHT Not Run Because RELEASE == FALSE'
      if: ${{ env.RELASE }}
      run: echo "CORRECT IT IS NOT A RELEASE"
    
